### PR TITLE
Add spotless for code format

### PR DESCRIPTION
**Pull request by wnbts**
Add [spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle) to check and apply a standard code format.

### CODE REVIEW

**Comment by ylwu-amzn** [comment]
> Could you add descriptions on readme on how to run spotless?

Seems the file format is for eclipse. Can it support Intellij IDEA? If I develop with Intellij IDEA, what should I do to make it compatible with this format? Can you add such information on readme too?

**Comment by wnbts** [comment]
> Could you add descriptions on readme on how to run spotless?

done.

**Comment by wnbts** [comment]
> > Could you add descriptions on readme on how to run spotless?
> 
> Seems the file format is for eclipse. Can it support Intellij IDEA? If I develop with Intellij IDEA, what should I do to make it compatible with this format? Can you add such information on readme too?

Intellij support eclipse format files.

**Comment by ylwu-amzn** [comment]
> > > Could you add descriptions on readme on how to run spotless?
> > 
> > 
> > Seems the file format is for eclipse. Can it support Intellij IDEA? If I develop with Intellij IDEA, what should I do to make it compatible with this format? Can you add such information on readme too?
> 
> Intellij support eclipse format files.

Thanks. Got it.
Open IntelliJ IDEA Settings → Code Style → Java, click Manage, and import that XML file by simply clicking Import.
Once import eclipse format file, we can use Intelij IDEA auto format short cut correctly.

**Pull request merged**
