### PR TITLE
1.9 backport

### PR DESCRIPTION
**Pull request by yizheliu-amazon**
*Issue #, if available:*

*Description of changes:*
Backport changes from PR https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/178 (c062263, commit after [ODFE 1.9 upgrade](https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/172)) to PR https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/214 (942a10a, commit before [ODFE 1.10 upgrade](https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/215)) 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kaituo** [comment]
CLI workflow fails.

**Comment by VijayanB** [comment]
@yizheliu-amazon can you include this commit(9df7b5980d66c88d2bf7aa57deb4c205d0b9e407)  as well to fix workflow failure?

**Comment by yizheliu-amazon** [comment]
> @yizheliu-amazon can you include this commit([9df7b59](https://github.com/opendistro-for-elasticsearch/anomaly-detection/commit/9df7b5980d66c88d2bf7aa57deb4c205d0b9e407)) as well to fix workflow failure?

Thanks for pointing it out. Cherry-picked it.

**Comment by yizheliu-amazon** [comment]
> CLI workflow fails.

After cherry-picking new changes, all workflows pass.

**Pull request merged**
