### PR TITLE
Add support filtering the data by one categorical variable

### PR DESCRIPTION
**Pull request by kaituo**
*Issue #, if available:*

*Description of changes:*

This PR is a conglomerate of the following PRs.

https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/247
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/249
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/250
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/252
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/253
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/256
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/257
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/258
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/259
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/260
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/261
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/262
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/263
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/264
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/265
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/266
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/267
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/268
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/269

This spreadsheet contains the mappings from files to PR number: https://quip-amazon.com/DiHkAmz9oSLu/HC-PR

Testing done:
1. Add unit tests except four classes (excluded in build.gradle). Will add them in the later PR.
2. Manual testing passes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yizheliu-amazon** [comment]
https://github.com/opendistro-for-elasticsearch/anomaly-detection/pull/270/checks?check_run_id=1266108900

`Rule violated for class com.amazon.opendistroforelasticsearch.ad.caching.PriorityCache.1: lines covered ratio is 0.60, but expected minimum is 0.75`

You may also increase coverage for it later to unblock build.

**Review by yizheliu-amazon — APPROVED** [review]
approving. please make sure build succeeds afterwards.

**Comment by kaituo** [comment]
> approving. please make sure build succeeds afterwards.

Sure, thanks YIzhe.

**Review by ylwu-amzn — APPROVED** [review]
LGTM. Thanks for the change

**Pull request merged**
